#! /bin/bash
set -e

DEFAULT_USER=$(gh api user -q .login)

REPO=$(gh api graphql --paginate  -F owner="${1:-$DEFAULT_USER}" -f query='
query ($owner: String!, $endCursor: String) {
    repositoryOwner(login: $owner) {
      repositories(
        first: 30
        after: $endCursor
        ){
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          nameWithOwner
        }
      }
    }
  }
' -q '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | fzf)

if [ $? -ne 0 ];then
  exit 1
fi


gh repo clone "${REPO}" "${@:2}"


